class("cok", "sifat").
class("bir", "sifat").
class("film", "isim").
class("hikaye", "isim").
class("filmi", "isim").
class("tekrar", "zarf").
class("iyi", "sifat").
class("guzel", "sifat").
class("bu", "sifat").
class("oyunculuklar", "isim").
class("uzun", "sifat").
class("filmin", "isim").
class("ve", "baglac").
class("daha", "zarf").
class("en", "zarf").
class("tek", "sifat").
class("icin", "edat").
class("hic", "zarf").
class("kitap", "isim").
class("filmdi", "fiil").
class("olmasina", "fiil").
class("tavsiye", "isim").
class("ragmen", "edat").
class("uyarlamasi", "fiil").
class("iyiydi", "fiil").
class("tam", "zarf").
class("var", "fiil").
class("kotu", "sifat").
class("fazla", "zarf").
class("orijinal", "sifat").
class("ama", "baglac").
class("konusu", "isim").
class("ederim", "fiil").
class("cogu", "isim").
class("izledigim", "sifat").
class("oyuncular", "isim").
class("yonetmenin", "isim").
class("kesinlikle", "zarf").
class("gercekten", "zarf").
class("olmus", "film").
class("begenmedim", "fiil").
class("begendim", "fiil").
class("takip", "fiil").
class("izlemek", "fiil").
class("olmasi", "fiil").
class("ozgunlukten", "isim").
class("izletiyor", "fiil").
class("ile", "baglac").
class("kopuktu", "fiil").
class("biraz", "zarf").
class("eglenceli", "fiil").
class("hicbir", "sifat").
class("arsivinde", "isim").
class("yasanan", "fiil").
class("son", "sifat").
class("travma", "isim").
class("inandirici", "sifat").
class("filmiydi", "fiil").
class("istemeyenler", "isim").
class("buldum", "fiil").
class("oyunculuk", "isim").
class("bunalima", "fiil").
class("o", "zamir").
class("alan", "isim").
class("metrajli", "sifat").
class("tadini", "fiil").
class("senenin", "isim").
class("rahatca", "zarf").
class("izlemesin", "fiil").
class("uc", "sifat").
class("aliciydi", "fiil").
class("yarisinda", "fiil").
class("gormedim", "fiil").
class("sanatsal", "sifat").
class("goz", "isim").
class("bati", "isim").
class("etmem", "fiil").
class("konusmalarin", "isim").
class("filme", "isim").
class("cizilmis", "fiil").
class("kitapta", "isim").
class("paraya", "isim").
class("tablosu", "isim").
class("cunku", "baglac").
class("surukleyici", "sifat").
class("herkese", "isim").
class("uzak", "sifat").
class("psikolojik", "sifat").
class("sokaktan", "isim").
class("ihlal", "isim").
class("orta", "isim").
class("etmeyi", "fiil").
class("imzasi", "isim").
class("kurtarmis", "fiil").
class("savasini", "isim").
class("uyumluydu", "fiil").
class("edilmisti", "fiil").
class("bence", "zarf").
class("derece", "isim").
class("da", "baglac").
class("etkilendigini", "fiil").
class("mukemmel", "sifat").
class("kitaptaki", "sifat").
class("yuzden", "zarf").
class("ortamlar", "isim").
class("beni", "zarf").
class("sekilde", "isim").
class("olayi", "isim").
class("otesinde", "zarf").
class("girer", "fiil").
class("vermeyen", "isim").
class("konusuna", "isim").
class("harry", "isim").
class("yapiyor", "fiil").
class("haketmiyor", "fiil").
class("genel", "isim").
class("konuyu", "isim").
class("sebebiyle", "zarf").
class("diyebilirim", "fiil").
class("arkadaslarla", "isim").
class("boylesini", "zarf").
class("beklentisiz", "zarf").
class("kalitesini", "isim").
class("bas", "isim").
class("bazinda", "isim").
class("benim", "zamir").
class("islenmis", "fiil").
class("sarmadi", "fiil").
class("geneli", "isim").
class("sonu", "isim").
class("dortluk", "isim").
class("basariliydi", "fiil").
class("zaman", "isim").
class("islemis", "fiil").
class("yasamak", "fiil").
class("yapmacikti", "fiil").
class("siradan", "sifat").
class("kamera", "isim").
class("bayildim", "fiil").
class("cevirsem", "fiil").
class("kendi", "zamir").
class("turlu", "sifat").
class("vasatti", "fiil").
class("kelime", "isim").
class("cubuk", "isim").
class("tutulmasi", "fiil").
class("gulduruyor", "fiil").
class("filmler", "isim").
class("begenmeyenler", "isim").
class("sonunu", "isim").
class("konsantre", "isim").
class("olmaya", "fiil").
class("animasyon", "isim").
class("potter", "isim").
class("fakat", "baglac").
class("haklari", "isim").
class("bakimindan", "").
class("sarsiyor", "fiil").
class("senaryosu", "isim").
class("sahneler", "isim").
class("gereken", "sifat").
class("abartili", "sifat").
class("izleyiciyi", "isim").
class("beklentinizi", "isim").
class("derken", "zarf").
class("baska", "sifat").
class("vahsi", "sifat").
class("savas", "isim").
class("kaybi", "isim").
class("her", "sifat").
class("klasik", "isim").
class("degil", "zarf").
class("serinin", "isim").
class("guzeldi", "fiil").
class("kadar", "edat").
class("sikiciydi", "fiil").
class("yapmis", "fiil").
class("iste", "edat").
class("fiyaskoydu", "fiil").
class("izlemeyi", "isim").
class("saatlerdir", "isim").
class("zor", "sifat").
class("vakit", "isim").
class("sakin", "sifat").
class("siradanin", "isim").
class("izlenebilecek", "sifat").
class("ekrana", "isim").
class("gidin", "fiil").
class("dram", "isim").
class("once", "edat").
class("dusunuyorum", "fiil").
class("sikayet", "isim").
class("dort", "isim").
class("dusurun", "fiil").
class("kisim", "isim").
class("amatordu", "fiil").
class("oynamis", "fiil").
class("kendime","zamir" ).
class("zorlastirmis", "fiil").
class("yonetmen", "isim").
class("atlanmis","zarf" ).
class("oynar","fiil" ).
class("etkiyi", "isim").
class("kurgu", "isim").
class("cikmis", "fiil").
class("komikti", "fiil").
class("donem", "sifat").
class("onermiyorum", "fiil").
class("dogal", "isim").
class("suresi", "isim").
class("berbat", "zarf").
class("hayatimda", "isim").
class("kullanilan", "sifat").
class("ucunu", "zarf").
class("etkiliyor","fiil" ).
class("lutfen", "edat").
class("sanki", "edat").
class("uzundu", "fiil").
class("isleyebilirdi", "fiil").
class("begenilen", "sifat").
class("gostermis", "zarf").
class("istedim", "sifat").
class("diye", "baglac").
class("cikartmis", "fiil").
class("kisi", "isim").
class("yorucuydu", "sifat").
class("egitici", "sifat").
class("sonra", "edat").
class("edilmeli", "fiil").
class("arasinda", "edat").
class("yogun", "sifat").
class("sureyi", "isim").
class("sinema", "isim").
class("yazik", "isim").
class("psikolojisini", "isim").
class("gidilir", "fiil").
class("enfes", "sifat").
class("gercekci", "sifat").
class("eglendik", "fiil").
class("aile", "isim").
class("yuzumu", "isim").
class("kotuydu", "fiil").
class("derinden", "zarf").
class("filmde", "isim").
class("ustu", "isim").
class("sikmadan", "zarf").
class("is", "isim").
class("zirveyi", "isim").
class("izleyince", "zarf").
class("nolan", "isim").
class("ikili", "sifat").
class("olarak", "zarf").
class("taysiye", "isim").
class("etmesi", "isim").
class("izliyorum", "fiil").
class("cagda", "isim").
class("ipin", "isim").
class("verdigim", "zarf").
class("cocuklar", "isim").
class("insani", "sifat").
class("uyudum", "fiil").
class("kitabin", "isim").
class("gormemistim", "fiil").
class("hayvan", "isim").
class("gordum", "fiil").
class("olay", "isim").
class("zamanina", "isim").
class("yoksun", "isim").
class("seyler", "isim").
class("olan", "zarf").
class("ben", "isim").
class("teknikleri", "isim").
class("solukta", "zarf").
class("yeni", "sifat").
class("isleyisi", "isim").
class("tarantino", "isim").
class("arasina", "isim").
class("verememis", "fiil").
class("aktarilmis", "fiil").
class("benzeri", "edat").
class("filmleri","isim" ).
class("ki","baglac" ).
class("islenis", "sifat").
class("havadaydi", "fiil").
class("cekildigi", "sifat").
class("heyecansiz", "zarf").
class("girdikce", "sifat").
class("olayim", "fiil").
class("harikaydi","fiil" ).
class("gore", "edat").
class("ortalama", "isim").
class("herkesin", "zamir").
class("annem", "isim").
class("gelemedim", "fiil").
class("de","baglac" ).
class("sikici", "zarf").
class("getirecek", "fiil").
class("hissetmek", "isim").
class("filmlerinden", "isim").
class("izlerken", "zarf").
class("eline","isim" ).
class("altinda", "sifat").
class("muhtesem", "zarf").
class("kacirmislar", "fiil").
class("bes","isim" ).
class("sevemeyecekler", "fiil").
class("uyarilmasi", "zarf").
class("yapitin","isim" ).
class("gordukten", "fiil").
class("varsa", "baglac").
class("olamadim", "fiil").
class("karakterleri", "isim").
class("veren", "sifat").
class("kopuk", "isim").
class("isleyis", "isim").
class("kilitliyor", "fiil").
class("hikayedeki", "fiil").
class("ortaya", "fiil").
class("neselenmek", "zarf").
class("aday", "isim").
class("ses", "isim").
class("dusulecek", "sifat").
class("izlenebilir","fiil" ).
class("tarihinin", "isim").
class("dunya","isin" ).
class("ilk", "sifat").
class("pesine","zarf" ).